### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by rsm123** [sle118/squeezelite-esp32#19]
Thank you for this great project! 
I try to compile with IDF4.0 with gcc 5.2.0 and getting following error:

In file included from /Users/rsm/esp/esp-idf/components/esp_eth/src/esp_eth.c:15:0:
/Users/rsm/esp/esp-idf/components/newlib/include/stdatomic.h: In function 'atomic_flag_test_and_set_explicit':
/Users/rsm/esp/esp-idf/components/newlib/include/stdatomic.h:271:31: error: request for member '__val' in something not a structure or union
  __atomic_exchange_n(&(object)->__val, desired, order)
                             
I am using espressif LyraT 4.3 development board.
Please help to resolve this error.

**Comment by sle118** [comment]
The easiest way to get on board is to use the master-cmake branch.

Install esp-idf branch release/v4 (you need to clone the branch so it is up to date). You also need to install the latest tools from espressif as gcc 5.2 will no longer be supported.
